### ISSUE TITLE
There is a small problem consultation

### ISSUE THREAD

**Issue by lki2019** [fozzysec/streamlink-chrome-extension-for-windows#1]
I see a project can use you-get call vlc local player to watch live and web video

https://github.com/xiaocsl/You-Get-Tool

------------------------

I would like to ask how the operation can use streamlink to see live and network video, automatically call mpv player, so save the resources!

**Comment by lki2019** [comment]
I think you can write a branch, improve the use of streamlink automatically call the local player mpv to watch streamlink support all video sites and live

**Comment by lki2019** [comment]
To achieve the following video demo effect

http://www.bilibili.com/video/av7997075/

**Comment by fozzysec** [comment]
That project uses tampermonkey to run scripts which I use Chrome extension to run scripts, that's the main difference. With the new plugin for douyu, you can play streams with one-click just by adding
```
player=mpv --cache 2048
```
to your streamlinkrc according to https://streamlink.github.io/cli.html#configuration-file.
If you want more websites to be supported just add your websites to the following file `streamlink-chrome-extension-for-windows/streamlink-chrome-extension/manifest.json` like this.
```
"content_scripts": [
    {
      "matches": [
        "http://*.douyu.com/*",
        "https://*.douyu.com/*",
        "http://*.douyutv.com/*",
        "https://*.douyutv.com/*",
        "https://*.panda.tv/*",
        "http://*.panda.tv/*",
        "http://*.bilibili.com/*",
        "https://*.bilibili.com/*"
      ],
```
The only problem with this project is that you need to enable the developer mode for Chrome ;D
P.S.
Don't forget to add mpv location to your `PATH` environment variable.

**Comment by lki2019** [comment]
I have feedback

I was WIN7 32 bit

Google Chrome 59.0.3071.115（正式版本） （32 位）


streamlink Can watch normally


figure 1：
http://i1.buimg.com/1949/5774602c65284346.jpg



but Streamlink Plugin failure






streamlinkrc   Use it    PotPlayer

-----install_url_scheme.reg

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\streamlink]
"URL Protocol"=""
@="URL:streamlink"

[HKEY_CLASSES_ROOT\streamlink\DefaultIcon]
@="\"D:\20160603\网盘下载工具\维棠\维棠下载器+v2.1.3.3+去广告绿色增强版\维棠下载器 v2.1.3.3 去广告绿色增强版\analyzers\livestreamer+streamlink\streamlink\streamlink谷歌浏览器扩展\streamlink-chrome-extension-for-windows-master\streamlinkrun.pl,1\""

[HKEY_CLASSES_ROOT\streamlink\shell]

[HKEY_CLASSES_ROOT\streamlink\shell\open]

[HKEY_CLASSES_ROOT\streamlink\shell\open\command]
@="\"D:\20160603\网盘下载工具\维棠\维棠下载器+v2.1.3.3+去广告绿色增强版\维棠下载器 v2.1.3.3 去广告绿色增强版\analyzers\livestreamer+streamlink\streamlink\streamlink谷歌浏览器扩展\streamlink-chrome-extension-for-windows-master\streamlinkrun.bat\" \"%1\""



streamlinkrun.bat

perl D:\20160603\网盘下载工具\维棠\维棠下载器+v2.1.3.3+去广告绿色增强版\维棠下载器 v2.1.3.3 去广告绿色增强版\analyzers\livestreamer+streamlink\streamlink\streamlink谷歌浏览器扩展\streamlink-chrome-extension-for-windows-master\streamlinkrun.pl %1


figure 2：
http://i4.piimg.com/1949/cd710b657890db7a.png


I can not call PotPlayer when I watch live on the web

**Comment by fozzysec** [comment]
@lki2019 你的路径包含空格。最好重命名下文件夹，去掉空格，另外然后直接修改`install_url_scheme.reg`和`streamlinkrun.bat`把你的路径填上去就可以了

**Comment by fozzysec** [comment]
比如你的路径是D:\我的文件\streamlink插件\streamlink.bat就这样子写就可以了
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\streamlink]
"URL Protocol"=""
@="URL:streamlink"

[HKEY_CLASSES_ROOT\streamlink\shell]

[HKEY_CLASSES_ROOT\streamlink\shell\open]

[HKEY_CLASSES_ROOT\streamlink\shell\open\command]
@="\"D:\\我的文件\\streamlink插件\\streamlinkrun.bat\" \"%1\""
```

```
perl D:\我的文件\streamlink插件\streamlinkrun.bat %1
```

**Comment by lki2019** [comment]
Or fail

I recorded my operation and you looked at it

https://pan.baidu.com/s/1jIR3rGa

**Comment by fozzysec** [comment]
the `streamlinkrun.bat` should be
```
perl D:\我的文件\streamlink插件\streamlinkrun.pl %1
```
sorry for typo.

**Comment by lki2019** [comment]
Or not, to flash over

**Comment by fozzysec** [comment]
You can add pause to your `streamlinkrun.bat` to see the error.
```
perl D:\我的文件\streamlink插件\streamlinkrun.pl %1
pause
```

**Comment by lki2019** [comment]
figure 1：
http://i1.buimg.com/1949/1c8679bdf8fbdd09.png
figure 2：
http://i1.buimg.com/1949/4dd7de40d397357c.png

PotPlayer does not come out

**Comment by fozzysec** [comment]
Directly download from https://raw.githubusercontent.com/fozzysec/streamlink-chrome-extension-for-windows/master/streamlinkrun.pl and have a try again. I didn't see any problem from the figure, there is no error message.

**Comment by lki2019** [comment]
图3：
http://i1.buimg.com/1949/9b987b947bc28592.png

**Comment by lki2019** [comment]
D:\20160603\浏览器\Google+Chrome+v59.0.3071.115\Chrome\59.0.3071.115>perl D:\我
的文件\streamlink插件\streamlinkrun.pl "streamlink://https://www.douyu.com/27487
4"
[cli][info] Found matching plugin douyutv for URL https://www.douyu.com/274874
Available streams: middle, middle2, source (worst), live (best)

D:\20160603\浏览器\Google+Chrome+v59.0.3071.115\Chrome\59.0.3071.115>pause
请按任意键继续. . .

**Comment by fozzysec** [comment]
add the following lines to your `streamlinkrc`
```
default-stream=best,rtmp,http
```
P.S. streamlink does not work with bilibili videos but work with bilibili live(whose url is the format if https://live.bilibili.com/xxx)

**Comment by lki2019** [comment]
OK。success

Thank you

**Comment by lki2019** [comment]
Plus what code, you can enter the live room automatically shield the current flash player


And then automatically call Streamlink Plugin, do not have to click again

That is, you can set, automatically call Streamlink Plugin

Or manually click on the Streamlink Plugin

**Comment by fozzysec** [comment]
Due to Chrome extension's privileges it is very difficult to call external url scheme without clicking on plugin and disabling flash.

**Comment by lki2019** [comment]
So it is
